app: github-action-demo
service: simple-rest-services
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  stage: '${opt:stage, ''development''}'
  stackName: '${self:service}-${self:provider.stage}'
  apiName: '${self:service}-${self:provider.stage}'
  region: '${env:AWS_REGION, ''us-west-2''}'
  memorySize: 128
  timeout: 30
  environment:
    LOG_LEVEL: debug
package:
  exclude:
    - tests/**
plugins:
  - serverless-deployment-bucket
  - serverless-plugin-typescript
  - serverless-offline
functions:
  my_hello:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get
