app: github-action-demo
service: simple-service
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${env:STAGE, self:custom.defaultStage}
  stackName: '${self:service}-${self:provider.stage}'
  apiName: '${self:service}-${self:provider.stage}'
  region: '${env:AWS_REGION, ''us-west-2''}'
  memorySize: 128
  timeout: 30
  environment:
    LOG_LEVEL: debug
custom:
  defaultStage: development
package:
  exclude:
    - tests/**
plugins:
  - serverless-deployment-bucket
  - serverless-plugin-typescript
  - serverless-offline
functions:
  my_hello:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get

  shopping:
    handler: index.shopping
    events:
      - http:
          path: bye
          method: get

  holiday:
    handler: index.holiday

  student:
    handler: student.getstudent
    events:
      - http:
          path: students
          method: get

    
